name: Metrics

on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 */24 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.Metrics }}
          
          # Options
          user: wy-luke
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Asia/Shanghai
          # repositories_forks: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          # plugin_introduction: yes
          
          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: yes       # Trim unused hours on daily chart
          
          plugin_lines: yes
          plugin_traffic: yes
          # plugin_notable: yes
          #plugin_skyline: yes
          
          #plugin_stackoverflow: yes
          #plugin_stackoverflow_user: 9522354
          
          plugin_wakatime: yes
          plugin_wakatime_token: 2aa5bdd4-bbf7-4bce-a437-9cc5247fa3cf   
